name: build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  create:
    tags:
      - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -B cmake-build -DCMAKE_BUILD_TYPE=Debug -Dbuild_tests=ON
          cmake --build cmake-build -- -j "$(nproc)"
          cd cmake-build/test
          ctest --stop-on-failure --output-on-failure
      - name: Upload torrest artifact
        uses: actions/upload-artifact@v2
        with:
          name: range-parser-linux-x64-debug
          path: cmake-build/librange_parser.a
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Perform release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
